### ISSUE TITLE
GET categories/<slug> does not work

### ISSUE THREAD

**Issue by maxpumperla** [readmeio/rdme#15]
Sorry for referring to the underlying HTTP API again, but in the end this is just a wrapper. I'm using Python to demonstrate my point. If I use:

```python
# Get category for slug
slug = 'subpage'
version = 'v1.0'
url = host + "/api/v1/categories/" + slug
headers = {'x-readme-version': version}
response = requests.request("GET", url, headers=headers, auth=auth)
print(response.text) 
```
That will result in an error message, although the page exists and has a category. I can even confirm this by reading slug details for the same doc:

```python
# Get doc/slug details WORKS
slug = 'subpage'
version = 'v1.0'
url = host + "/api/v1/docs/" + slug
headers = {'x-readme-version': version}
response = requests.request("GET", url, headers=headers, auth=auth)
print(response.text)
details = json.loads(response.content)
category = details.get('category')
```

so either I'm doing something fundamentally wrong or the endpoint doesn't work as expected

**Comment by domharrington** [comment]
I think there's maybe a misunderstanding here of what this endpoint is supposed to do.

/api/v1/categories/slug - returns with the category object associated to that category slug

/api/v1/docs/slug - returns with the doc object associated to the doc slug (which will return with the category id required to update the doc)

The category slug isn't typically surfaced by default in the UI, but it can be useful if you wanted to built a wrapper around the API using the category slugs instead of using the ids.

**Comment by maxpumperla** [comment]
@domharrington thank you. note that as a workaround I'm perfectly happy with my second option above, document details:

```python
category = details.get('category')
```
that works well to retrieve the "category slug" from a "document slug".
