### ISSUE TITLE
Syncing OpenAPI files to a version with a dash submits to the wrong version

### ISSUE THREAD

**Issue by JesseTG** [readmeio/rdme#387]
I'm trying to sync a proof-of-concept OpenAPI document to my employer's ReadMe instance. We have a private staging version named `v2-stage`, as well as a live version named `v2`.

However, when I sync to `v2-stage` using the following command...

```
rdme openapi --version=v2-stage --key=$README_API_KEY ./openapi.yml
```

...`rdme` syncs to `v2` instead. This resulted in heavily work-in-progress documentation briefly going live. Everything after the `-` was ignored.

As a workaround, I renamed `v2-stage` to `v3`. The command then worked as expected.

**Comment by kanadgupta** [comment]
Hi @JesseTG! Apologies for the issues. This is because of some confusing behavior where the [ReadMe API's Get Version endpoint](https://docs.readme.com/reference/getversion) would previously expect semver-formatted versions (e.g. `v2.0.0-stage`) rather than the actual name of the version (e.g. `v2-stage`). We have a fix for this behavior going out today. Will close this issue out when it's live.

**Comment by JesseTG** [comment]
Thanks!

**Comment by kanadgupta** [comment]
The changes are now live. Please reach out if you're still seeing this issue. Thanks @JesseTG!

**Comment by JesseTG** [comment]
Will do, I appreciate it.
