### ISSUE TITLE
rdme npm sdk methods are available?

### ISSUE THREAD

**Issue by gauravshukla303** [readmeio/rdme#506]
Hi, I am someone who is trying to accommodate the rdme CLI commands through a nodejs script within the code. 
I am trying to use execSync method of child_process in nodejs but not getting positive results. in Local it works but when I push to my bitbucket repository and when the bitbucket pipeline triggers 'ts-node testScript.ts', I get error like 
```
"error: unknown option '--key=mykey'
Error: Command failed: npx -y rdme@7.2.0 openapi 'temp/readme/myyamlfile.yaml' --key=mykey --id=mydefId"
```

So, here is my eventual question, 

- do we have sdk methods to achieve this task? 
- If not, can you suggest how should I do it? and how to remove this kind of error?

**Comment by kanadgupta** [comment]
Hi @gauravshukla303! I'm having trouble following what exactly you're trying to do here. Unless you're adding custom functionality, we recommend installing `rdme` via `npm` rather than cloning the files and running it locally. Check out our [setup guidance](https://github.com/readmeio/rdme#setup) for more information.

If you're trying to develop on the codebase locally, we use the entry file located at `bin/rdme` for invoking the `rdme` commands. You can read more about that in [our contributing docs](https://github.com/readmeio/rdme/blob/main/CONTRIBUTING.md#running-shell-commands-locally-).
