### ISSUE TITLE
Fresh CLI install not working, nor is npx: Cannot find module 'oas/dist/lib/reducer'

### ISSUE THREAD

**Issue by gp-rigado** [readmeio/rdme#703]
CLI is not working
I was messing around and uninstalled/reinstalled rdme CLI and now I can't get it working at all, with an install or with npx. With node 14 or 16. 

```
❯ nvm use 16
Now using node v16.18.0 (npm v8.19.2)
❯ npm install -g rdme@latest
changed 279 packages, and audited 280 packages in 5s
34 packages are looking for funding
run `npm fund` for details
found 0 vulnerabilities
❯ rdme
node:internal/modules/cjs/loader:988
throw err;
^
Error: Cannot find module 'oas/dist/lib/reducer'
```

**Comment by erunion** [comment]
I relocated the `reducer` library within our [oas](https://npm.im/oas) package earlier today and tagged it to a minor release instead of a full major because we only use it within this CLI tool and I thought it'd be a safe release. I've reverted that change out of that package and tagged a [20.1.2 release there](https://github.com/readmeio/oas/releases/tag/20.1.2). rdme installs are working fine again now.

![Screen Shot 2022-12-05 at 7 57 40 PM](https://user-images.githubusercontent.com/33762/205809663-670c8719-4269-4b20-8ca4-18826e05b6d5.png)

Slightly concerning that rdme installs off npm don't install the packages that we have pinned in `package-lock.json`. Thanks for bringing this to our attention, and my apologies you had to experience this.
