### ISSUE TITLE
CLI interactivity is frustrating for CI

### ISSUE THREAD

**Issue by hhuuggoo** [readmeio/rdme#711]
I just spent time attempting to put our readme.com workflow into github actions. I realize that readme.com can generate github actions for me - but the approach taken in the docs donot work for us because we generate version numbers based on branches, therefore the IDs are not known ahead of time.

The documentation suggests that certain parameters, such as `--fork` or `--update` are optional. Technically true, if you are working in an interactive context, but when trying to develop CI workflows, these are no longer optional, since your action won't run without them.

**Comment by kanadgupta** [comment]
Thanks for the feedback @hhuuggoo and apologies for the frustrating experience. For that reason I recommend running your commands in a local CLI-friendly environment to ensure the commands run without prompts prior to deploying them as CI workflows (which is an advantage that `rdme` has over many other GitHub Actions out there). If the GitHub Actions syntax isn't working for you, you could always run `rdme` via `npx`. For example, instead of this:

```yml
- name: Run command via GitHub Actions
  uses: readmeio/rdme@v8
  with:
    rdme: [your command here]
```

You could do something like this:

```yml
- name: Run command via npx
  run: npx rdme@v8 [your command here]
```

The former is better in that you can update it automatically via [Dependabot](https://docs.github.com/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot), but the latter might be better for chaining commands together.

The dual CLI / GitHub Actions setup we leverage in `rdme` allows us to ship well-tested automations faster and provide a better developer experience in some ways, but it does have its downsides. If you have any specific ideas for improving upon the `rdme` experience, we'd love to hear it!
