### ISSUE TITLE
Doc Migration Tool

### ISSUE THREAD

**Issue by garrett-wade** [readmeio/rdme#719]
# Challenge
In order to sync a document between multiple versions or projects a separate file must be maintained with the correct category or parentDoc ids. 
# Solution
A command the accepts two project keys and versions, as well as a configuration file of all categories and documents to sync between the two projects slugs.

**Comment by kanadgupta** [comment]
Hey @garrett-wade! There are parts of this that could be addressed by improving our import/export support (which is on our radar but is unfortunately blocked by some broader internal engineering efforts), but in the interim I actually just open-sourced the codebase we used recently for a content migration of our own. You can find it here: https://github.com/readmeio/content-migration

We don't plan on maintaining that repository nor incorporating that work into `rdme` since migrations are complex and those scripts are unlikely to handle every use case perfectly — but they should be a solid starting point that addresses most of the challenges you've described. Let me know what you think!
