### ISSUE TITLE
In GHES - Unable to resolve action `readmeio/rdme@v8`, repository not found on this server.

### ISSUE THREAD

**Issue by RizwanaUKG** [readmeio/rdme#726]
I have created a self hosted github runner in Github enetrprise account and I am unable to use the rdme

**Comment by RizwanaUKG** [comment]
![image](https://user-images.githubusercontent.com/114471357/210266581-0027d343-3a66-4a49-82cf-a3ef1868ee59.png)

**Comment by erunion** [comment]
Hi, it looks like because our action is public and not a repository on your organizations GHES instance you'll need to configure your GHES instance to have access to public actions and workflows.

https://docs.github.com/en/enterprise-server@3.3/admin/github-actions/managing-access-to-actions-from-githubcom/enabling-automatic-access-to-githubcom-actions-using-github-connect
