### ISSUE TITLE
Unknown error uploading json

### ISSUE THREAD

**Issue by paololim** [readmeio/rdme#84]
We are currently running into the following error when trying to use this `rdme` cli, specifically the generic
```
There was an error uploading!
```
It would be helpful to have a `--verbose` flag to state what the error actually is or just actually put the error message directly in the string above.

Thanks!

**Comment by erunion** [comment]
That's not great. Can you make a request manually to our API with cURL and give me the response that that's returning? https://docs.readme.com/reference#post_swagger

We're probably not handling a special error case for whatever the problem is.

**Comment by RAM237** [comment]
Same here. I've read thru rdme documentation and haven't found the ability to get the reason for error.
"There was an error uploading!" sounds too generic.

**Comment by MikhailTamarinFlipdish** [comment]
Same here. Any updates on this? The problem is that GUI has successful update.

<img width="270" alt="image" src="https://user-images.githubusercontent.com/71270031/121366558-40602780-c942-11eb-9c70-769313bb9b01.png">

**Comment by erunion** [comment]
@MikhailTamarinFlipdish (and @RAM237) are you able to share here the file that's throwing this error but showing a success in the dash console?

**Comment by MikhailTamarinFlipdish** [comment]
@erunion Sure. Here it is. 
[swagger.json.zip](https://github.com/readmeio/rdme/files/6629060/swagger.json.zip)

**Comment by MikhailTamarinFlipdish** [comment]
@erunion Any updates on this? Issue is still there.

**Comment by erunion** [comment]
@MikhailTamarinFlipdish Turns out that that our API is timing out while processing that file and returning an HTML body, which rdme doesn't know how to interpret. I've added some better error handling for this in https://github.com/readmeio/rdme/pull/340, but the best way to get around this is to chunk your file up into 2 files. It's not a great solution for you I know, but it'll do until we're able to prioritize the necessary infrastructure changes that need to happen to make these timeouts go away.
