### ISSUE TITLE
Incorrect $ref resolution

### ISSUE THREAD

**Issue by jebertz** [readmeio/rdme#907]
$refs are resolved using the relative path from where rdme is run, not the relative path to the referring document as it is specified in https://spec.openapis.org/oas/v3.1.0#relativeReferencesURI.  This is causing a lot of issues in our ability to automate.

**Comment by kanadgupta** [comment]
Hi @jebertz!

By default, we require references from the root of the directory. Relative references are supported via [the `workingDirectory` argument](https://github.com/readmeio/rdme/tree/v8#override-the-working-directory). Have you tried using that?

And thanks for pointing out that language in the spec, I wasn't aware of that. We're working towards a v9 release and we're hoping to deprecate the `workingDirectory` flag since it's proven to be an issue in certain CI environments. We rely on [`json-schema-ref-parser`](https://github.com/APIDevTools/json-schema-ref-parser) for resolving `$ref` pointers so this is a tricky problem for us. It looks like the latest release includes https://github.com/APIDevTools/json-schema-ref-parser/pull/305 which might be helpful here. Will look into this further with @erunion once he's back.

Thanks!

Tagging a few potentially related issues below for posterity:

https://github.com/APIDevTools/json-schema-ref-parser/issues/199
https://github.com/APIDevTools/json-schema-ref-parser/issues/251

**Comment by jebertz** [comment]
Thank you for the quick response.  We had tried workingDirectory, but were apparently using it incorrectly on the first try.  After your message, we tried the `workingDirectory` again and got it working this time, so thank you!

If it's helpful to you for future designs, we're trying to run the validate as a job in github actions on PR/push for any files that changed and then run sync on merge.  We very heavily use $refs and are also only trying to lint one directory (we have the OAS for internal, our legacy external - v2, and our new external - v3 in one repo and only want to validate the v3).  We are also using spectral and were evaluating a few other tools as well that expected the refs to be relative (which was why we didn't just change them).  Thanks again!

**Comment by kanadgupta** [comment]
@jebertz great to hear that the `workingDirectory` flag was working for you! Out of curiosity, were you able to get the flag working properly in GitHub Actions? If so, we'd love to learn more about your setup — we've had some issues getting that flag working properly in CI environments and I'd love to see what you did!

**Comment by kanadgupta** [comment]
Got it, thanks for sending that across! I'm going to close this out since it appears this specific issue around `$ref` resolution is resolved, but feel free to open up more issues as you run into them.

**Comment by jebertz** [comment]
thank you!
