### ISSUE TITLE
Limit a doc to be viewed by user type

### ISSUE THREAD

**Issue by garrett-wade** [readmeio/rdme#992]
Hey!

Often we have an API that is not ready for customers yet, but teams want to view it in our developer portal. These APIs are part of the same API spec. We have looked into ReadMe Micro, but found it to not be what we needed. It would awesome if there was a way to specify if a doc within a project can be viewed by a Teammate, End-user, or Both!

Thank you,

Garrett

**Comment by kanadgupta** [comment]
Hey @garrett-wade! This currently isn't supported and we don't have any immediate plans to work on this unfortunately, but we've added a feature request internally and you should receive updates as we have 'em!

As a temporary workaround, I'd recommend publishing/hiding pages: https://docs.readme.com/main/docs/preview-and-publish-pages#hidden-pages

We also support this via `rdme` and our API via the `hidden` parameter: https://docs.readme.com/main/reference/createdoc

Since we're tracking this internally[^1] and this is outside of the scope of `rdme`, I'm going to close this out — but if you have any general product feature requests, your best bet is [submitting a request on our product feedback site](https://feedback.readme.com) or [getting in touch with our support team](mailto:support@readme.io).

Thanks!

[^1]: [internal link](https://readme.productboard.com/all-notes/notes/39421064)
